modLoader="javafml"
loaderVersion="[47,)"
license="GNU GPL 3.0"
issueTrackerURL="https://github.com/GenerationsMod/Generations-Core/issues"

[[mods]]
modId="generations_core"
version="${version}"
displayName="Generations-Core"
authors="J.T. McQuigg (JT122406), Waterpicker, Stampede"
credits="Generations Development Team"
logoFile="icon.png"
description='''
Core mod for Generations. Required for all other Generations mods.
Contains Blocks, Items, Entities, and other things that are used by all other Generations mods.
'''

[[dependencies.generations_core]]
   modId="forge"
   mandatory=true
   versionRange="[47.1,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.generations_core]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20.1,)"
   ordering="NONE"
   side="BOTH"
